### ISSUE TITLE
Add integration tests for testing Nemo-Serve with PubAnnotation files

### ISSUE THREAD

**Issue by gaurav** [RENCI-NER/nemo-serve#18]
The [PubAnnotation JSON format](http://www.pubannotation.org/docs/annotation-format/) is a nice format for storing text annotations, and the one we plan to use for testing and benchmarking in RENCI-NER. I think it would be useful to have a PubAnnotation-based integration for Nemo-Serve, which would:
1. Go through  a list of PubAnnotation files from a directory -- since these will be stored on GitHub, they would need to be text that we have permission to share with attribution, such as from the [PubMed Central](https://en.wikipedia.org/wiki/PubMed_Central) repository. (e.g. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8261293/)
2. For each each PubAnnotation file, submit the text to NemoServe and retrieve the list of denotations it returns. The test passes if Nemo-Serve retrieves at least one annotation for each text.
3. Create a report file that returns the list of all known denotations in each test file, i.e. those stored in the test file as well as those returned by Nemo-Serve. That way, we can look for text that Nemo-Serve identified correctly, misidentified, and failed to identify at all.

The report file might look something like this, but please feel free to change it to something that makes more sense:
| Test file | Text | Span | Class from test file | ID from test file | Label from test file | Class from Nemo-Serve | 
|---------|------|------|------|----|-------------------|---------------------------|
| pmc8261293.json | Allergic | 0:8 | biolink:Disease | MONDO:1234 | Allergy | biolink:Disease |
| pmc8261293.json | asthma | 10:16 | biolink:Disease | MONDO:5678 | asthma | biolink:Disease |
| pmc8261293.json | Allergic asthma | 0:16 | biolink:Disease | MONDO:3456 | Allergenic asthma | biolink:Disease |
| pmc8261293.json | DEX | 45:48 | biolink:SmallMolecule | CHEBI:1234 | Dexamethasone | |
| pmc8261293.json | infiltration | 50:62 | | | | biolink:Phenotype |

**Comment by mbacon-renci** [comment]
Migrated to Jira: Add integration tests for testing Nemo-Serve with PubAnnotation files
